export const CLIENT_CRED_SCOPE = 'https://api.ebay.com/oauth/api_scope'
export const AUTH_CRED_SCOPE = 'https://auth.ebay.com/oauth2/authorize'
export const CLIENT_GRANT_TYPE = 'client_credentials'
export const USER_GRANT_TYPE = 'authorization_code'
export const EBAY_BASAE_URL = 'api.ebay.com'
export const EBAY_AUTH_URL = 'auth.ebay.com'
